FROM registry.fedoraproject.org/fedora-toolbox:43

RUN echo 'max_parallel_downloads=10' | sudo tee --append /etc/dnf/dnf.conf
RUN sudo dnf install --assumeyes --quiet fish dnf-plugins-core && \
    sudo dnf update --assumeyes --quiet

COPY packages.txt /
RUN sudo dnf install --assumeyes --quiet $(<packages.txt) \
    && rm packages.txt \
    && sudo dnf clean all

ENV CONTAINER_ID fedora-rpm
