local pkg = require('dotfiles.package')
local use = pkg.use

use('nvim-lua/plenary.nvim')
use('neovim/nvim-lspconfig')
use({ 'nvim-treesitter/nvim-treesitter', branch = 'main', run = 'TSUpdateSync' })
use('inko-lang/inko.vim')
use('yorickpeterse/rust.vim')
use('yorickpeterse/nvim-grey')
use('yorickpeterse/nvim-window')
use('yorickpeterse/nvim-pqf')
use('yorickpeterse/nvim-dd')
use('yorickpeterse/nvim-tree-pairs')
use('nvim-tree/nvim-web-devicons')
use('mfussenegger/nvim-lint')
use('stevearc/oil.nvim')
use('stevearc/conform.nvim')
use('dcampos/nvim-snippy')
use('folke/snacks.nvim')

pkg.install()
