local pkg = require('dotfiles.package')
local use = pkg.use

use('nvim-lua/plenary.nvim')
use('neovim/nvim-lspconfig')
use({ 'nvim-treesitter/nvim-treesitter', run = 'TSUpdateSync' })
use('inko-lang/inko.vim')
use('yorickpeterse/rust.vim')
use('yorickpeterse/nvim-grey')
use('yorickpeterse/nvim-window')
use('yorickpeterse/nvim-pqf')
use('yorickpeterse/nvim-dd')
use('yorickpeterse/nvim-tree-pairs')
use('kyazdani42/nvim-web-devicons')
use('nvim-telescope/telescope.nvim')
use({ 'nvim-telescope/telescope-fzf-native.nvim', run = '!make' })
use('mfussenegger/nvim-lint')
use('stevearc/oil.nvim')
use('stevearc/conform.nvim')
use('stevearc/dressing.nvim')
use('dcampos/nvim-snippy')

pkg.install()
