FROM quay.io/toolbx-images/alpine-toolbox:edge

# qmk-cli is still in the testing repository.
RUN echo '@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
RUN apk add --update qmk-cli@testing make
ENV CONTAINER_ID qmk
