---
name: Container
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the image to build'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  NAMESPACE: yorickpeterse/dotfiles

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: containers/${{ inputs.name }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}:${{ inputs.name }}
