---
name: Containers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'containers/*/Dockerfile'
      - .github/workflows/*

permissions:
  contents: read
  packages: write

jobs:
  fedora:
    uses: ./.github/workflows/container.yml
    with:
      name: fedora
  fedora-rpm:
    uses: ./.github/workflows/container.yml
    with:
      name: fedora-rpm
  tumbleweed:
    uses: ./.github/workflows/container.yml
    with:
      name: tumbleweed
